### ISSUE TITLE
importer never called

### ISSUE THREAD

**Issue by matthieusieben** [csstools/postcss-sass#16] opened 2019-03-20 14:25 UTC
It seems there is an issue with `sass` as the `importer()` function never gets called. Switching back to `node-sass` fixes the issue.

**Comment by matthieusieben** [comment] 2019-03-20 14:27
To test this, simply add the following to the `importer` and run the tests:
```js
	importer(id, parentId, done) {
		console.error('In importer', id)

		// ...
	}
```

You won't see `In importer` in the logs, unless you use `node-sass` (but then, the tests will fail...)

**Comment by chalkygames123** [comment] 2019-03-26 03:54
As mentioned in https://github.com/maoberlehner/node-sass-magic-importer/issues/191, that is likely due to the `postcss-sass` overriding the `importer` option.

**Comment by matthieusieben** [comment] 2019-03-28 07:06
What I mean is that postcss-sass 's importer is never called.

Clone this repo, add a log statement **inside postcss-sass** importer and run the tests.

You won't see the log statement.

**Comment by matthieusieben** [comment] 2019-04-03 12:23
Actually, it seems the importer is called only when `sass` does not find the path by itself using the `includePath`.

**Comment by tsmd** [comment] 2019-06-12 17:08
AFAIK, this is by design, actually.
Here is designer's comment:
https://github.com/sass/dart-sass/issues/574#issuecomment-457026289

I think you should find another way to build the dependency graph.

**Comment by Steakeye** [comment] 2020-09-28 19:51
@matthieusieben I forked the library and have a PR, why don't you checkout my version and see if it works for you? I think it solves your problem as I had a similar issue.

**Comment by romainmenke** [comment] 2023-12-28 13:57
Closing as this is working as the `dart-sass` maintainers intended.

**Closed as completed by romainmenke** 2023-12-28 13:57 UTC
